/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VanguardRouteImport } from './routes/vanguard'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as RetentionProtocolRouteImport } from './routes/retention-protocol'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OutcomeForumRouteImport } from './routes/outcome-forum'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as AiReadinessRouteImport } from './routes/ai-readiness'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as CodexSlugRouteImport } from './routes/codex.$slug'
import { Route as AiReadinessSurveyRouteImport } from './routes/ai-readiness.survey'

const VanguardRoute = VanguardRouteImport.update({
  id: '/vanguard',
  path: '/vanguard',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RetentionProtocolRoute = RetentionProtocolRouteImport.update({
  id: '/retention-protocol',
  path: '/retention-protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomeForumRoute = OutcomeForumRouteImport.update({
  id: '/outcome-forum',
  path: '/outcome-forum',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReadinessRoute = AiReadinessRouteImport.update({
  id: '/ai-readiness',
  path: '/ai-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const CodexSlugRoute = CodexSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CodexRoute,
} as any)
const AiReadinessSurveyRoute = AiReadinessSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => AiReadinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai-readiness': typeof AiReadinessRouteWithChildren
  '/codex': typeof CodexRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/outcome-forum': typeof OutcomeForumRoute
  '/pricing': typeof PricingRoute
  '/retention-protocol': typeof RetentionProtocolRoute
  '/subscribe': typeof SubscribeRoute
  '/vanguard': typeof VanguardRoute
  '/ai-readiness/survey': typeof AiReadinessSurveyRoute
  '/codex/$slug': typeof CodexSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai-readiness': typeof AiReadinessRouteWithChildren
  '/codex': typeof CodexRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/outcome-forum': typeof OutcomeForumRoute
  '/pricing': typeof PricingRoute
  '/retention-protocol': typeof RetentionProtocolRoute
  '/subscribe': typeof SubscribeRoute
  '/vanguard': typeof VanguardRoute
  '/ai-readiness/survey': typeof AiReadinessSurveyRoute
  '/codex/$slug': typeof CodexSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai-readiness': typeof AiReadinessRouteWithChildren
  '/codex': typeof CodexRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/outcome-forum': typeof OutcomeForumRoute
  '/pricing': typeof PricingRoute
  '/retention-protocol': typeof RetentionProtocolRoute
  '/subscribe': typeof SubscribeRoute
  '/vanguard': typeof VanguardRoute
  '/ai-readiness/survey': typeof AiReadinessSurveyRoute
  '/codex/$slug': typeof CodexSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/ai-readiness'
    | '/codex'
    | '/insights'
    | '/login'
    | '/outcome-forum'
    | '/pricing'
    | '/retention-protocol'
    | '/subscribe'
    | '/vanguard'
    | '/ai-readiness/survey'
    | '/codex/$slug'
    | '/insights/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/ai-readiness'
    | '/codex'
    | '/insights'
    | '/login'
    | '/outcome-forum'
    | '/pricing'
    | '/retention-protocol'
    | '/subscribe'
    | '/vanguard'
    | '/ai-readiness/survey'
    | '/codex/$slug'
    | '/insights/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/ai-readiness'
    | '/codex'
    | '/insights'
    | '/login'
    | '/outcome-forum'
    | '/pricing'
    | '/retention-protocol'
    | '/subscribe'
    | '/vanguard'
    | '/ai-readiness/survey'
    | '/codex/$slug'
    | '/insights/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AiReadinessRoute: typeof AiReadinessRouteWithChildren
  CodexRoute: typeof CodexRouteWithChildren
  InsightsRoute: typeof InsightsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OutcomeForumRoute: typeof OutcomeForumRoute
  PricingRoute: typeof PricingRoute
  RetentionProtocolRoute: typeof RetentionProtocolRoute
  SubscribeRoute: typeof SubscribeRoute
  VanguardRoute: typeof VanguardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vanguard': {
      id: '/vanguard'
      path: '/vanguard'
      fullPath: '/vanguard'
      preLoaderRoute: typeof VanguardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retention-protocol': {
      id: '/retention-protocol'
      path: '/retention-protocol'
      fullPath: '/retention-protocol'
      preLoaderRoute: typeof RetentionProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcome-forum': {
      id: '/outcome-forum'
      path: '/outcome-forum'
      fullPath: '/outcome-forum'
      preLoaderRoute: typeof OutcomeForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-readiness': {
      id: '/ai-readiness'
      path: '/ai-readiness'
      fullPath: '/ai-readiness'
      preLoaderRoute: typeof AiReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/codex/$slug': {
      id: '/codex/$slug'
      path: '/$slug'
      fullPath: '/codex/$slug'
      preLoaderRoute: typeof CodexSlugRouteImport
      parentRoute: typeof CodexRoute
    }
    '/ai-readiness/survey': {
      id: '/ai-readiness/survey'
      path: '/survey'
      fullPath: '/ai-readiness/survey'
      preLoaderRoute: typeof AiReadinessSurveyRouteImport
      parentRoute: typeof AiReadinessRoute
    }
  }
}

interface AiReadinessRouteChildren {
  AiReadinessSurveyRoute: typeof AiReadinessSurveyRoute
}

const AiReadinessRouteChildren: AiReadinessRouteChildren = {
  AiReadinessSurveyRoute: AiReadinessSurveyRoute,
}

const AiReadinessRouteWithChildren = AiReadinessRoute._addFileChildren(
  AiReadinessRouteChildren,
)

interface CodexRouteChildren {
  CodexSlugRoute: typeof CodexSlugRoute
}

const CodexRouteChildren: CodexRouteChildren = {
  CodexSlugRoute: CodexSlugRoute,
}

const CodexRouteWithChildren = CodexRoute._addFileChildren(CodexRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AiReadinessRoute: AiReadinessRouteWithChildren,
  CodexRoute: CodexRouteWithChildren,
  InsightsRoute: InsightsRouteWithChildren,
  LoginRoute: LoginRoute,
  OutcomeForumRoute: OutcomeForumRoute,
  PricingRoute: PricingRoute,
  RetentionProtocolRoute: RetentionProtocolRoute,
  SubscribeRoute: SubscribeRoute,
  VanguardRoute: VanguardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
